"""Pluggable execution targets, command translation, and task execution."""

from test_runner.execution.command_translator import (
    CommandTranslator,
    CommandValidationError,
    FrameworkTranslator,
    ScriptTranslator,
    TestCommand,
    TranslationResult,
    UnsupportedFrameworkError,
)
from test_runner.execution.executor import (
    ExecutionCallback,
    ExecutionPolicy,
    TaskAttemptRecord,
    TaskExecutor,
)
from test_runner.execution.script_executor import (
    OutputCallback,
    ScriptCommand,
    ScriptExecutor,
    ScriptResult,
    ScriptType,
    classify_command,
)
from test_runner.execution.factory import (
    ExecutionTargetFactory,
    TargetCreator,
    TargetInfo,
    execution_target,
    get_factory,
    reset_factory,
)
from test_runner.execution.remote_ci import (
    CIJobResult,
    CIJobStatus,
    CIProvider,
    CIProviderConfig,
    CIProviderError,
    GitHubActionsProvider,
    JenkinsProvider,
    RemoteCIExecutionTarget,
)
from test_runner.execution.targets import (
    DockerConfig,
    DockerTarget,
    ExecutionResult,
    ExecutionStatus,
    ExecutionTarget,
    LocalTarget,
    RemoteCITarget,
    TargetRegistry,
)

__all__ = [
    "CIJobResult",
    "CIJobStatus",
    "CIProvider",
    "CIProviderConfig",
    "CIProviderError",
    "CommandTranslator",
    "CommandValidationError",
    "DockerConfig",
    "DockerTarget",
    "ExecutionTargetFactory",
    "ExecutionCallback",
    "ExecutionPolicy",
    "ExecutionResult",
    "ExecutionStatus",
    "ExecutionTarget",
    "FrameworkTranslator",
    "GitHubActionsProvider",
    "JenkinsProvider",
    "LocalTarget",
    "OutputCallback",
    "RemoteCIExecutionTarget",
    "RemoteCITarget",
    "ScriptCommand",
    "ScriptExecutor",
    "ScriptResult",
    "ScriptTranslator",
    "ScriptType",
    "TargetCreator",
    "TargetInfo",
    "TargetRegistry",
    "TaskAttemptRecord",
    "TaskExecutor",
    "TestCommand",
    "TranslationResult",
    "UnsupportedFrameworkError",
    "classify_command",
    "execution_target",
    "get_factory",
    "reset_factory",
]
